packages:
  - apps/*
  - packages/*

catalog:
  '@eslint/eslintrc': ^3
  '@phosphor-icons/react': ^2.1.10
  '@tailwindcss/postcss': 4.1.13
  '@types/node': ^20
  '@types/pg': ^8.15.5
  '@types/react': 19.2.7
  '@types/react-dom': 19.2.3
  ajv: ^8.17.1
  bun: ^1.2.23
  dotenv: ^17.2.2
  drizzle-kit: ^0.31.4
  drizzle-orm: ^0.44.4
  eslint: ^9
  eslint-config-next: 16.0.7
  lodash: ^4.17.21
  lucide-react: ^0.453.0
  next: 16.0.7
  pg: ^8.13.1
  prettier: ^3.6.2
  react: 19.2.1
  react-dom: 19.2.1
  tailwindcss: ^4
  tsx: ^4.20.6
  turbo: ^2.5.8
  typescript: 5.9.2
  vitest: ^3.2.4
  zod: ^4.1.11

ignoredBuiltDependencies:
  - bun

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
  - unrs-resolver
