export const dbContentItems = [
  {
    id: 'a4941f6f5f5f',
    source: 'bibleproject',
    content_type: 'video',
    title: 'Book of Acts Summary | Watch an Overview Video (Part 1)',
    description:
      'What is the book of Acts about in the Bible? Watch as we explain its major themes and gain a deeper understanding of its place in the biblical story.',
    url: 'https://bibleproject.com/videos/acts-1-12',
    media_url:
      'https://stream.mux.com/zEm8b16B4p7NWXnDvS5nu25nSExRoI6EKP5GhHAWg2Q/high.mp4',
    thumbnail_url:
      'https://ik.imagekit.io/bpweb1/web/media/video-images/new-testament-overview/acts-1-12/tr:q-65,w-720/acts-1-12_16.9.jpg',
    upload_date: '2016-10-04 00:00:00.000000',
    duration_seconds: 496,
    series_title: 'New Testament Overviews',
    poster_images: [
      'https://d1bsmz3sdihplr.cloudfront.net/media/Posters%20Download/49-Acts-FNL.jpg',
    ],
    og_title: 'Book of Acts Summary | Watch an Overview Video (Part 1)',
    og_description:
      'What is the book of Acts about in the Bible? Watch as we explain its major themes and gain a deeper understanding of its place in the biblical story.',
    bible_book: 'Acts',
    full_text: null,
    date: null,
    created_at: '2025-10-09 17:47:28.462141',
    updated_at: '2025-10-09 17:47:28.462141',
  },
  {
    id: 'a9da9dacefd3',
    source: 'bibleproject',
    content_type: 'video',
    title: 'Book of Acts Summary | Watch an Overview Video (Part 2)',
    description:
      'What is the book of Acts about in the Bible? Watch as we explain its major themes and gain a deeper understanding of its place in the biblical story.',
    url: 'https://bibleproject.com/videos/acts-13-28',
    media_url:
      'https://stream.mux.com/JGLOuBLC800dwIB2EWj027EN9e6K42poyigmI600moX00008/high.mp4',
    thumbnail_url:
      'https://ik.imagekit.io/bpweb1/web/media/video-images/new-testament-overview/acts-13-28/tr:q-65,w-720/acts-13-28_16.9.jpg',
    upload_date: '2016-10-10 00:00:00.000000',
    duration_seconds: 484,
    series_title: 'New Testament Overviews',
    poster_images: [
      'https://d1bsmz3sdihplr.cloudfront.net/media/Posters%20Download/49-Acts-FNL.jpg',
    ],
    og_title: 'Book of Acts Summary | Watch an Overview Video (Part 2)',
    og_description:
      'What is the book of Acts about in the Bible? Watch as we explain its major themes and gain a deeper understanding of its place in the biblical story.',
    bible_book: 'Acts',
    full_text: null,
    date: null,
    created_at: '2025-10-09 18:06:38.301928',
    updated_at: '2025-10-09 18:06:38.301928',
  },
  {
    id: '9ed804520520',
    source: 'bibleproject',
    content_type: 'video',
    title: 'Book of Romans Summary | Watch an Overview Video (Part 1)',
    description:
      'What is the book of Romans about in the Bible? Watch as we explain its major themes and gain a deeper understanding of its place in the biblical story.',
    url: 'https://bibleproject.com/videos/romans-1-4',
    media_url:
      'https://stream.mux.com/JOwtd4wJBaE4tNEpG29osk7YpsfJGd1hvFP9RL2nPWY/high.mp4',
    thumbnail_url:
      'https://ik.imagekit.io/bpweb1/web/media/video-images/new-testament-overview/romans-1-4/tr:q-65,w-720/romans-1-4_16.9.jpg',
    upload_date: '2016-10-19 00:00:00.000000',
    duration_seconds: 467,
    series_title: 'New Testament Overviews',
    poster_images: [
      'https://d1bsmz3sdihplr.cloudfront.net/media/Posters%20Download/50_Romans.jpg',
    ],
    og_title: 'Book of Romans Summary | Watch an Overview Video (Part 1)',
    og_description:
      'What is the book of Romans about in the Bible? Watch as we explain its major themes and gain a deeper understanding of its place in the biblical story.',
    bible_book: 'Romans',
    full_text: null,
    date: null,
    created_at: '2025-10-09 18:06:38.301928',
    updated_at: '2025-10-09 18:06:38.301928',
  },
  {
    id: 'bc5ddd7dd002',
    source: 'bibleproject',
    content_type: 'video',
    title: 'Book of Romans Summary | Watch an Overview Video (Part 2)',
    description:
      'What is the book of Romans about in the Bible? Watch as we explain its major themes and gain a deeper understanding of its place in the biblical story.',
    url: 'https://bibleproject.com/videos/romans-5-16',
    media_url:
      'https://stream.mux.com/01O8p00kAKeMNeSBelNy100lSoMoFcCZ01W6rU1McatNQ8w/high.mp4',
    thumbnail_url:
      'https://ik.imagekit.io/bpweb1/web/media/video-images/new-testament-overview/romans-5-16/tr:q-65,w-720/romans-5-16_16.9.jpg',
    upload_date: '2016-10-19 00:00:00.000000',
    duration_seconds: 551,
    series_title: 'New Testament Overviews',
    poster_images: [
      'https://d1bsmz3sdihplr.cloudfront.net/media/Posters%20Download/50_Romans.jpg',
    ],
    og_title: 'Book of Romans Summary | Watch an Overview Video (Part 2)',
    og_description:
      'What is the book of Romans about in the Bible? Watch as we explain its major themes and gain a deeper understanding of its place in the biblical story.',
    bible_book: 'Romans',
    full_text: null,
    date: null,
    created_at: '2025-10-09 18:06:38.301928',
    updated_at: '2025-10-09 18:06:38.301928',
  },
  {
    id: 'a222f340d2b1',
    source: 'bibleproject',
    content_type: 'video',
    title: 'Book of 1 Corinthians Summary | Watch an Overview Video',
    description:
      'What is the book of 1 Corinthians about in the Bible? Watch as we explain its major themes and gain a deeper understanding of its place in the biblical story.',
    url: 'https://bibleproject.com/videos/1-corinthians',
    media_url:
      'https://stream.mux.com/WieKKhX26bqP4x9OKvQUmBKSHvk38EcEeTilyn5lXP4/high.mp4',
    thumbnail_url:
      'https://ik.imagekit.io/bpweb1/web/media/video-images/new-testament-overview/1-corinthians/tr:q-65,w-720/1-corinthians_16.9.jpg',
    upload_date: '2015-05-18 00:00:00.000000',
    duration_seconds: 527,
    series_title: 'New Testament Overviews',
    poster_images: [
      'https://d1bsmz3sdihplr.cloudfront.net/media/Posters%20Download/52-53-Corinthians.jpg',
    ],
    og_title: 'Book of 1 Corinthians Summary | Watch an Overview Video',
    og_description:
      'What is the book of 1 Corinthians about in the Bible? Watch as we explain its major themes and gain a deeper understanding of its place in the biblical story.',
    bible_book: '1 Corinthians',
    full_text: null,
    date: null,
    created_at: '2025-10-09 18:06:38.301928',
    updated_at: '2025-10-09 18:06:38.301928',
  },
];

export const glooAffiliateRecommendations = [
  {
    item_id: 'c2808635-7291-4fad-beb5-61053c604903',
    author: ['Revive Our Hearts'],
    filename: 'reviving-a-lifeless-bible-study-IxRunf2LVl8zyigWEewhQ.txt',
    denomination: '',
    duration: '',
    item_title: 'Reviving a Lifeless Bible Study',
    item_subtitle: '',
    item_image:
      'https://d3tfn18lzrilkz.cloudfront.net/blogs.crossmap.com/app/uploads/2023/03/28225039/kelly-sikkema-YnRNdB-XTME-unsplash-3-qEOQpTU2-scaled.jpg',
    item_url:
      'https://blogs.crossmap.com/stories/reviving-a-lifeless-bible-study-IxRunf2LVl8zyigWEewhQ',
    item_tags: [
      'Bible',
      'Devotionals',
      'Revival',
      'Spiritual Awareness & Enlightenment',
    ],
    h2_id: '',
    h2_title: '',
    h2_subtitle: '',
    h2_image: '',
    h2_url: '',
    h2_tags: null,
    h3_id: '',
    h3_title: '',
    h3_subtitle: '',
    h3_image: '',
    h3_url: '',
    h3_tags: null,
    h2_summary: '',
    publication_date: 'Jan 13 2022',
    publisher: 'Crossmap',
    publisher_id: '1b653cec-d9ae-4310-9c66-394fcb950726',
    publisher_url: 'www.crossmap.com',
    publisher_logo:
      'https://dapologeticsimages.s3.us-east-1.amazonaws.com/logos/logo_1751930142598.png',
    summary: '',
    type: 'article',
    hosted_url:
      'https://blogs.crossmap.com/stories/reviving-a-lifeless-bible-study-IxRunf2LVl8zyigWEewhQ',
    snippet_count: 1,
    cumulative_certainty: 0.7929625511169434,
  },
  {
    item_id: '5e725ac3-8b2b-4f3b-984a-34eb6f5b64c0',
    author: ['Mary Rooney Armand'],
    filename:
      'how-to-study-the-bible-and-grow-closer-to-god-5-powerful-ways-JReeErp5zpbwmiK0VcJkS.txt',
    denomination: '',
    duration: '',
    item_title:
      'How to Study the Bible and Grow Closer to God: 5 Powerful Ways',
    item_subtitle: '',
    item_image:
      'https://d3tfn18lzrilkz.cloudfront.net/blogs.crossmap.com/images/1738197581-vBj2zuJqiCLROcHNKSwWL.png',
    item_url:
      'https://blogs.crossmap.com/stories/how-to-study-the-bible-and-grow-closer-to-god-5-powerful-ways-JReeErp5zpbwmiK0VcJkS',
    item_tags: '',
    h2_id: '',
    h2_title: '',
    h2_subtitle: '',
    h2_image: '',
    h2_url: '',
    h2_tags: null,
    h3_id: '',
    h3_title: '',
    h3_subtitle: '',
    h3_image: '',
    h3_url: '',
    h3_tags: null,
    h2_summary: '',
    publication_date: 'Jan 29 2025',
    publisher: 'Crossmap',
    publisher_id: '1b653cec-d9ae-4310-9c66-394fcb950726',
    publisher_url: 'www.crossmap.com',
    publisher_logo:
      'https://dapologeticsimages.s3.us-east-1.amazonaws.com/logos/logo_1751930142598.png',
    summary: '',
    type: 'article',
    hosted_url:
      'https://blogs.crossmap.com/stories/how-to-study-the-bible-and-grow-closer-to-god-5-powerful-ways-JReeErp5zpbwmiK0VcJkS',
    snippet_count: 1,
    cumulative_certainty: 0.7888249158859253,
  },
  {
    item_id: 'ce22e22b-7663-452f-91dc-a555b0a0e61a',
    author: ['Scott Pauley'],
    filename:
      '7-ingredients-for-fruitful-bible-study-XKVI5SJfXaO22THOEX6jg.txt',
    denomination: '',
    duration: '',
    item_title: '7 Ingredients for Fruitful Bible Study',
    item_subtitle: '',
    item_image:
      'https://d3tfn18lzrilkz.cloudfront.net/blogs.crossmap.com/images/1740458731-QC7t8tn6wHtqhs5BJ-3uG.jpeg',
    item_url:
      'https://blogs.crossmap.com/stories/7-ingredients-for-fruitful-bible-study-XKVI5SJfXaO22THOEX6jg',
    item_tags: '',
    h2_id: '',
    h2_title: '',
    h2_subtitle: '',
    h2_image: '',
    h2_url: '',
    h2_tags: null,
    h3_id: '',
    h3_title: '',
    h3_subtitle: '',
    h3_image: '',
    h3_url: '',
    h3_tags: null,
    h2_summary: '',
    publication_date: 'Feb 24 2025',
    publisher: 'Crossmap',
    publisher_id: '1b653cec-d9ae-4310-9c66-394fcb950726',
    publisher_url: 'www.crossmap.com',
    publisher_logo:
      'https://dapologeticsimages.s3.us-east-1.amazonaws.com/logos/logo_1751930142598.png',
    summary: '',
    type: 'article',
    hosted_url:
      'https://blogs.crossmap.com/stories/7-ingredients-for-fruitful-bible-study-XKVI5SJfXaO22THOEX6jg',
    snippet_count: 1,
    cumulative_certainty: 0.7845126986503601,
  },
  {
    item_id: 'c2d076a6-b3d9-4ba0-aa56-4537d307e7ea',
    author: ['Hannah'],
    filename: 'effective-methods-to-study-the-bible-cmRra88RC1MDIaapwuK-q.txt',
    denomination: '',
    duration: '',
    item_title: 'Effective methods to study the Bible',
    item_subtitle: '',
    item_image:
      'https://d3tfn18lzrilkz.cloudfront.net/blogs.crossmap.com/images/1688977961-jGd8Nx8O9JaQ1ljA4NeWw.jpeg',
    item_url:
      'https://blogs.crossmap.com/stories/effective-methods-to-study-the-bible-cmRra88RC1MDIaapwuK-q',
    item_tags: [
      'Bible',
      'Learning',
      'New Testament',
      'Old Testament',
      'Spiritual growth',
    ],
    h2_id: '',
    h2_title: '',
    h2_subtitle: '',
    h2_image: '',
    h2_url: '',
    h2_tags: null,
    h3_id: '',
    h3_title: '',
    h3_subtitle: '',
    h3_image: '',
    h3_url: '',
    h3_tags: null,
    h2_summary: '',
    publication_date: 'Jul 10 2023',
    publisher: 'Crossmap',
    publisher_id: '1b653cec-d9ae-4310-9c66-394fcb950726',
    publisher_url: 'www.crossmap.com',
    publisher_logo:
      'https://dapologeticsimages.s3.us-east-1.amazonaws.com/logos/logo_1751930142598.png',
    summary: '',
    type: 'article',
    hosted_url:
      'https://blogs.crossmap.com/stories/effective-methods-to-study-the-bible-cmRra88RC1MDIaapwuK-q',
    snippet_count: 1,
    cumulative_certainty: 0.7838960289955139,
  },
  {
    item_id: 'bdff4fea-f8e7-4d3d-84eb-c7661c0ecfbd',
    author: ['Joseph Antonio Liao'],
    filename:
      'how-to-meditate-on-gods-word-top-tips-to-remember-4_-UmiWDUBOTdL19PHZdS.txt',
    denomination: '',
    duration: '',
    item_title: "How to meditate on God's Word: Top tips to remember",
    item_subtitle: '',
    item_image:
      'https://d3tfn18lzrilkz.cloudfront.net/blogs.crossmap.com/app/uploads/2023/05/10071426/aaron-burden-n_ZpsjsqHM-unsplash-Rg5dRKTh-scaled.jpg',
    item_url:
      'https://blogs.crossmap.com/stories/how-to-meditate-on-gods-word-top-tips-to-remember-4_-UmiWDUBOTdL19PHZdS',
    item_tags: [
      'Bible',
      'Christian Living',
      'Christianity',
      'Evergreen content',
    ],
    h2_id: '',
    h2_title: '',
    h2_subtitle: '',
    h2_image: '',
    h2_url: '',
    h2_tags: null,
    h3_id: '',
    h3_title: '',
    h3_subtitle: '',
    h3_image: '',
    h3_url: '',
    h3_tags: null,
    h2_summary: '',
    publication_date: 'May 10 2023',
    publisher: 'Crossmap',
    publisher_id: '1b653cec-d9ae-4310-9c66-394fcb950726',
    publisher_url: 'www.crossmap.com',
    publisher_logo:
      'https://dapologeticsimages.s3.us-east-1.amazonaws.com/logos/logo_1751930142598.png',
    summary: '',
    type: 'article',
    hosted_url:
      'https://blogs.crossmap.com/stories/how-to-meditate-on-gods-word-top-tips-to-remember-4_-UmiWDUBOTdL19PHZdS',
    snippet_count: 1,
    cumulative_certainty: 0.7828542590141296,
  },
];
